---
title: "Supplementary methods"
author: "Jonathan Marshall"
date: "27 May 2017"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Supplementary methods

### Derivation of balance equations for risk and biodiversity

Suppose we are to divide a given area into $m$ identical fragments with the same shape as the original.

Then the total biodiversity across the $m$ fragments will be
$$
\begin{aligned}
S(m) &= A^z \left[1 - \prod_i \left( 1 - \frac{A_i^z}{A^z} \right)\right]\\
  &= A^z \left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]\\
\end{aligned}
$$
and hence the ratio of the total biodiversity of the $m$ fragments compared to the biodiversity
in the area is given by
$$
\frac{S(m)}{S(1)} = 1 - \left( 1 - \frac{1}{m^z} \right)^m
$$

Using this, we can derive formulae for risk if biodiversity is balanced, and for biodiversity if risk is balanced.

Assume that risk is balanced between the $m$ and 1 fragment cases. As risk is biodiversity times the perimeter, then assuming the perimeter is proportional to the square root of area, we see that
$$
\mathsf{Risk}(1, A) = k A^{z} A^{1/2} = k A ^ {z + 1/2}
$$
for some constant $k$. In the case where we have $m$ fragments, the total risk is the sum of the individual risks, and hence
$$
\mathsf{Risk}(m, \hat{A}) = m \mathsf{Risk}(1, \frac{\hat{A}}{m}) = m k \left(\frac{\hat{A}}{m}\right)^{z + 1/2}
$$
If the risk in these cases are to be balanced, the total area in the $m$ fragment case, $\hat{A}$ may be found
$$
\begin{aligned}
\mathsf{Risk}(m, \hat{A}) &= \mathsf{Risk}(1, A)\\
m k \left(\frac{\hat{A}}{m}\right)^{z + 1/2} &= k A ^ {z + 1/2}\\
\left(\frac{\hat{A}}{m}\right)^{z + 1/2} &= \frac{A ^ {z + 1/2}}{m}\\
\frac{\hat{A}}{m} &= \frac{A}{m^\frac{1}{z+1/2}}\\
\hat{A} &= A\frac{m}{m^\frac{1}{z+1/2}}\\
        &= A m^\frac{z-1/2}{z+1/2}
\end{aligned}
$$
Substituting this new total area, we find the biodiversity ratio in the case of $m$ fragments to be
$$
\begin{aligned}
\mathsf{BR}(m) &= \frac{\hat{A}^z}{A^z}\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]\\
&= m^{z\frac{z-1/2}{z+1/2}}\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]
\end{aligned}
$$
In the same way, we can first balance biodiversity so that
$$
\begin{aligned}
B(m, \tilde{A}) &= B(1, A)\\
\tilde{A}^z\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right] &= A^z\\
\tilde{A}^z &= \frac{A^z}{\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]}\\
\tilde{A} &= \frac{A}{\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]^\frac{1}{z}}\\
\end{aligned}
$$
and hence the risk ratio in the case of $m$ fragments is
$$
\begin{aligned}
\mathsf{RR}(m) &= \frac{m k \left(\frac{\tilde{A}}{m}\right)^{z + 1/2}}{k A ^ {z + 1/2}}\\
& = \frac{m k \left(\frac{A}{m\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]^\frac{1}{z}}\right)^{z + 1/2}}{k A ^ {z + 1/2}}\\
& = \frac{m}{m^{z + 1/2}\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]^\frac{z + 1/2}{z}}\\
& = \frac{1}{m^{z - 1/2}\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]^\frac{z + 1/2}{z}}.\\
\end{aligned}
$$

### Behaviour of balancing equations

For the values of the power $z$ that are biologically plausible ($z < \frac{1}{2}$), we can see that if risk is balanced, then biodiversity is necessarily reduced, while if biodiversity is balanced then risk is necessarily increased. This can be seen as follows.

If $z < \frac{1}{2}$ then $z - \frac{1}{2} < 0$, and given $m \geq 1$ we have
$$
m^{z - \frac{1}{2}} < 1
$$
It is clear that
$$
0 < 1 - \left(1 - \frac{1}{m^z}\right)^m \leq 1
$$
with equality holding only if $z = 0$. From this, and noting that the fraction $\frac{z}{z+1/2}$ is non-negative it is clear that $RR(m) > 1$ and $BR(m) < 1$ for $0 < z < \frac{1}{2}$.

Further, in the case where $z=\frac{1}{2a}$ we have
$$
BR(m) = 1 - \left(1 - \frac{1}{m^{1/{2}}}\right)^m
$$
and
$$
RR(m) = \left[1 - \left(1 - \frac{1}{m^{1/{2}}}\right)^m\right]^{-2}
$$
so that $BR(m) \rightarrow 1^{-}$ and $RR(m) \rightarrow 1^{+}$ as $m \rightarrow \infty$. Thus, only larger values of $z$ that have not been observed in practice allow risk and biodiversity to remain balanced as fragmentation increases.

Extending the above to the case where there is a dilution effect $d < 1$ changes Equations XXX and YYY to
$$
\begin{aligned}
\mathsf{BR}(m) &= m^{z\frac{dz-1/2}{dz+1/2}}\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]\\
\mathsf{RR}(m) & = \frac{1}{m^{dz - 1/2}\left[1 - \left( 1 - \frac{1}{m^z} \right)^m\right]^\frac{dz + 1/2}{z}}
\end{aligned}
$$
for which $BR(m) > 1$ and $RR(m) < 1$ for $z < \frac{1}{2d}$. And for $z = \frac{1}{2d}$ we have $BR(m) \rightarrow 1^{-}$ and $RR(m) \rightarrow 1^{+}$ as $m \rightarrow \infty$ as before. As $d < 1$, this is a larger range for $z$ than we have in the absence of a dilution effect, and hence for biologically plausible powers $z$, either risk increases or biodiversity decreases with fragmentation.
